version: 0.0
os: linux
files:
- source: /
  destination: /tmp
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    timeout: 300
  AfterInstall:
  - location: scripts/application_start.sh
    timeout: 300
